---
- name: Générer le fichier .env pour Web
  template:
    src: templates/web.env.j2
    dest: "{{ web_path }}/.env"
    mode: "0600"
  tags: [web, env]

- name: Déployer l'app Web
  become: true
  ansible.builtin.command: docker compose up -d --build
  args:
    chdir: "{{ web_path }}"
  tags: [web, deploy]