services:
  software:
    build:
      context: ../..
      dockerfile: apps/software/Dockerfile
    container_name: software
    ports:
      - "3010:8080"
    networks:
      - traefik-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.software.rule=Host(`software.bastiencouder.com`)"
      - "traefik.http.routers.software.entrypoints=websecure"
      - "traefik.http.routers.software.tls.certresolver=myresolver"
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  traefik-net:
    external: true