---
      
- name: Déployer l'application sur les hôtes maîtres
  hosts: master
  become: true
  vars_files:
    - vars/defaults.yml
    - secrets/secret.{{ env }}.yml
  roles:
    - { role: docker, tags: [docker] }
    - { role: global, tags: [global] }
    - { role: email, tags: [email] }
    - { role: web, tags: [web, apps] }
    - { role: software, tags: [software, apps] }
    - { role: monitoring, tags: [monitoring] }