services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: email-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    networks:
      - traefik-net
    ports:
      - "15672:15672"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rabbitmq.rule=Host(`rabbit.bastiencouder.com`)"
      - "traefik.http.routers.rabbitmq.entrypoints=websecure"
      - "traefik.http.routers.rabbitmq.tls.certresolver=myresolver"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  maildev:
    image: maildev/maildev
    container_name: email-maildev
    networks:
      - traefik-net
    ports:
      - "1080:1080"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.maildev.rule=Host(`mail.bastiencouder.com`)"
      - "traefik.http.routers.maildev.entrypoints=websecure"
      - "traefik.http.routers.maildev.tls.certresolver=myresolver"
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:1080"]
      interval: 30s
      timeout: 10s
      retries: 5

  worker:
    build:
      context: ../..
      dockerfile: apps/email/Dockerfile
    container_name: email-worker
    depends_on:
      - rabbitmq
      - maildev
    environment:
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      RABBITMQ_URL: ${RABBITMQ_URL}
    networks:
      - traefik-net
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "ps aux | grep index.ts | grep -v grep"]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  traefik-net:
    external: true