name: Checks

on:
  pull_request:
    branches: [main, develop, staging]
  push:
    branches: [main, develop, staging]

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Simuler lint
        run: echo "Lint OK"

  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Simuler test
        run: echo "Tests OK"

  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Simuler build
        run: echo "Build OK"